//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartNotes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListThing
    {
        public int stvarID { get; set; }
        public string nazivStvari { get; set; }
        public Nullable<byte> prekrizeno { get; set; }
        public int ListaID { get; set; }
    
        public virtual List List { get; set; }
    }
}
